/* Generated By:JavaCC: Do not edit this line. SimpleExpConstants.java */
package org.das2.qds.util.dd;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleExpConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 4;
  /** RegularExpression Id. */
  int EQUAL = 5;
  /** RegularExpression Id. */
  int SEMI = 6;
  /** RegularExpression Id. */
  int OPEN_PAR = 7;
  /** RegularExpression Id. */
  int CLOSE_PAR = 8;
  /** RegularExpression Id. */
  int NUMBER = 9;
  /** RegularExpression Id. */
  int IDENTIFIER = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"+\"",
    "\"=\"",
    "\";\"",
    "\"(\"",
    "\")\"",
    "<NUMBER>",
    "<IDENTIFIER>",
  };

}
