/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.virbo.filters;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import org.virbo.dataset.QDataSet;
import org.virbo.dsops.Ops;

/**
 *
 * @author aluthens
 */
public class TrimFilterEditorPanel extends AbstractFilterEditorPanel {

    /**
     * Creates new form TrimTest
     */
    public TrimFilterEditorPanel() {
        initComponents();
    }
    public static void main( String[] args ) {
        FilterEditorPanel filter= new TrimFilterEditorPanel();
        QDataSet ds= Ops.ripplesTimeSeries(1440); //FiltersChainPanel.getExampleDataSet("rank1TimeSeries");
        int dataSize= getDataSetSize(ds);
        filter.setFilter("|trim(0,"+dataSize+")");
        filter.setInput(ds);
        JOptionPane.showMessageDialog( null, filter);
        System.err.println( filter.getFilter() );
    }
    
    private static int getDataSetSize(QDataSet ds){
        int dataSize=ds.length();
        return dataSize;
    }
    
    @Override
    public void setInput(QDataSet listSize){
        endLabel.setText( String.format( "Up to but not including (%d bins):",listSize.length() ) );
    }
    
    
    @Override
    public void setFilter(String filter) {
        
        Pattern p= Pattern.compile("\\|trim\\(\\s*(\\d+)\\s*\\,\\s*(\\d+)\\s*\\)");
        Matcher m= p.matcher(filter);
        
        if ( m.matches() ) {
            lowerBound.setText(m.group(1));
            upperBound.setText( m.group(2) );
        }
        else {
            //String maxUpperBound=m.group(3);
            lowerBound.setText( "0" );
            upperBound.setText( "10" );
        }
    }

    //test for subversion commit
    @Override
    public String getFilter() {
        String upperBoundPoint = upperBound.getText().replaceAll("\\s","");
        String lowerBoundPoint = lowerBound.getText().replaceAll("\\s","");
        return "|trim(" + lowerBoundPoint + "," + upperBoundPoint +  ")";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        endLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        upperBound = new javax.swing.JTextField();
        lowerBound = new javax.swing.JTextField();

        endLabel.setText("Up to but not including:");
        endLabel.setToolTipText("Negative indeces are allowed, so -1 refers to the last index.");

        jLabel3.setText("Trim from index:");

        upperBound.setText("-1");

        lowerBound.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(endLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upperBound, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lowerBound, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lowerBound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(endLabel)
                    .addComponent(upperBound, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel endLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField lowerBound;
    private javax.swing.JTextField upperBound;
    // End of variables declaration//GEN-END:variables
}
