/*
 * BoxZoomDialog.java
 *
 * Created on May 16, 2007, 7:36 AM
 */

package edu.uiowa.physics.pw.das.event;

import javax.swing.JOptionPane;

/**
 *
 * @author  jbf
 */
public class BoxZoomDialog extends javax.swing.JPanel {
    
    BoxZoomMouseModule module;

    /** Creates new form BoxZoomDialog */
    public BoxZoomDialog( BoxZoomMouseModule module ) {
        initComponents();
        this.module= module;
        zoomYButton.setAction( module.getZoomYAction() );
        zoomXButton.setAction( module.getZoomXAction() );
        zoomBoxButton.setAction( module.getZoomBoxAction() );
    }
    
    String getXRange(  )  {
        return xRangeTextField.getText();
    }
    
    String getYRange( )  {
        return yRangeTextField.getText();
    }
    
    public boolean isAutoBoxZoom() {
        return autoCheckBox.isSelected();
    }
    
    public boolean isConstrainProportions() {
        return constrainProportionsCheckBox.isSelected();
    }
            
    public boolean isDisablePopup() {
        return disablePopupCheckBox.isSelected();
    }
            
    public void setDisablePopup( boolean v ) {
        disablePopupCheckBox.setSelected(v);
    }
    
    public void setConstrainProportions( boolean v ) {
        constrainProportionsCheckBox.setSelected(v);
    }
    
    public void setAutoBoxZoom( boolean v ) {
        autoCheckBox.setSelected(v);
    }
    
    public void setXRange( String s ) {
        this.xRangeTextField.setText(s);
    }
    
    public void setYRange( String s ) {
        this.yRangeTextField.setText(s);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        xRangeTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        yRangeTextField = new javax.swing.JTextField();
        zoomYButton = new javax.swing.JButton();
        zoomBoxButton = new javax.swing.JButton();
        zoomXButton = new javax.swing.JButton();
        autoCheckBox = new javax.swing.JCheckBox();
        disablePopupCheckBox = new javax.swing.JCheckBox();
        constrainProportionsCheckBox = new javax.swing.JCheckBox();

        jLabel1.setText("X:");

        jLabel2.setText("Y:");

        zoomYButton.setText("<html>z<br>o<br>o<br>m<br>Y</html>");
        zoomYButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        zoomBoxButton.setText("<html>Zoom<br>Box</html>");

        zoomXButton.setText("zoom X");

        autoCheckBox.setText("auto box zoom");
        autoCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        autoCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        autoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoCheckBoxActionPerformed(evt);
            }
        });

        disablePopupCheckBox.setText("disable popup");
        disablePopupCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        disablePopupCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        disablePopupCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disablePopupCheckBoxActionPerformed(evt);
            }
        });

        constrainProportionsCheckBox.setText("constrain proportions");
        constrainProportionsCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        constrainProportionsCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        constrainProportionsCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                constrainProportionsCheckBoxActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(xRangeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(yRangeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(zoomYButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(zoomXButton)
                                    .add(zoomBoxButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                            .add(constrainProportionsCheckBox)
                            .add(autoCheckBox)
                            .add(layout.createSequentialGroup()
                                .add(17, 17, 17)
                                .add(disablePopupCheckBox)))))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {xRangeTextField, yRangeTextField}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.linkSize(new java.awt.Component[] {zoomBoxButton, zoomXButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(xRangeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(yRangeTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(zoomBoxButton)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(zoomXButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(zoomYButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(constrainProportionsCheckBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(autoCheckBox)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(disablePopupCheckBox)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void disablePopupCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disablePopupCheckBoxActionPerformed
        if ( disablePopupCheckBox.isSelected() ) {
            JOptionPane.showConfirmDialog(this,"Popup may be re-enabled via the plot's property editor");
        }
        module.guiChanged();
    }//GEN-LAST:event_disablePopupCheckBoxActionPerformed

    private void constrainProportionsCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_constrainProportionsCheckBoxActionPerformed
        module.guiChanged();
    }//GEN-LAST:event_constrainProportionsCheckBoxActionPerformed

    private void autoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoCheckBoxActionPerformed
        disablePopupCheckBox.setEnabled( autoCheckBox.isSelected() );
        if ( !autoCheckBox.isSelected() ) disablePopupCheckBox.setSelected(false);
        module.guiChanged();
    }//GEN-LAST:event_autoCheckBoxActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox autoCheckBox;
    private javax.swing.JCheckBox constrainProportionsCheckBox;
    private javax.swing.JCheckBox disablePopupCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField xRangeTextField;
    private javax.swing.JTextField yRangeTextField;
    private javax.swing.JButton zoomBoxButton;
    private javax.swing.JButton zoomXButton;
    private javax.swing.JButton zoomYButton;
    // End of variables declaration//GEN-END:variables
    
}
